"""Guarded constant-volume internal-fan edits; native acceptance required separately."""

import math
from copy import deepcopy

from nx_mcp.runtime import NXToolError
from nx_mcp.simcenter.internal_fan import snapshot


def inspect(boundary, sim, *, require_member=True):
    """Read the supported fan binding and the invariants this operation preserves."""
    if boundary.OwningPart != sim or boundary.DescriptorName != "Internal Fan":
        raise NXToolError("NX_SIM_SELECTION_OWNER", "Select an Internal Fan in this SIM")
    p = boundary.PropertyTable
    selectors = {
        k: p.GetIntegerPropertyValue(k)
        for k in ("Mode Option", "Alignment", "Swirl", "Controller Type")
    }
    if selectors != {"Mode Option": 3, "Alignment": 0, "Swirl": 0, "Controller Type": 0}:
        raise NXToolError(
            "NX_SIM_UNSUPPORTED_CONFIGURATION",
            "Requires prescribed volume flow, normal alignment, no swirl/controller",
        )
    wrapper = p.GetScalarFieldWrapperPropertyValue("Volume Flow")
    expression = wrapper.GetExpression() if wrapper else None
    if expression is None or wrapper.GetField() is not None:
        raise NXToolError("NX_SIM_UNSUPPORTED_CONFIGURATION", "Requires constant expression flow")
    try:
        literal = float(expression.GetFormula())
    except (ValueError, TypeError) as exc:
        raise NXToolError(
            "NX_SIM_UNSUPPORTED_CONFIGURATION", "Parameterized flow is unsupported"
        ) from exc
    value, unit = p.GetScalarWithDataPropertyValue("Volume Flow")
    if (
        unit is None
        or unit.Name != "CubicMeterPerSecond"
        or not math.isfinite(value)
        or value <= 0
        or not math.isfinite(literal)
        or expression.Units is None
        or expression.Units.Name != "CubicMeterPerSecond"
        or not math.isclose(literal, value, rel_tol=1e-12)
    ):
        raise NXToolError(
            "NX_SIM_UNSUPPORTED_CONFIGURATION", "Requires positive finite flow in m3/s"
        )
    if require_member and int(boundary.Tag) not in {
        int(x.Tag) for x in sim.Simulation.ActiveSolution.GetBcs()
    }:
        raise NXToolError("NX_SIM_SELECTION_OWNER", "Fan must belong to the active solution")
    _, members = boundary.TargetSetManager.GetTargetSetMembers(0)
    targets = sorted((int(m.Obj.Tag), str(m.SubType), int(m.SubId)) for m in members)
    if not targets:
        raise NXToolError("NX_SIM_CONFIGURATION_MISSING", "Fan has no target faces")
    direction = p.GetVectorPropertyValue("Orientation Vector")
    v = direction.Vector
    heat, heat_unit = p.GetBaseScalarWithDataPropertyValue("Heat Generated by Fan")
    return {
        "flow": float(value),
        "wrapper": int(wrapper.Tag),
        "invariants": {
            "name": boundary.Name,
            "selectors": selectors,
            "targets": targets,
            "direction": [int(direction.Tag), v.X, v.Y, v.Z],
            "heat": [heat, heat_unit.Name if heat_unit else None],
        },
    }


def set_membership(session, sim, boundary, enabled):
    """Change only direct fan membership; exported effectiveness needs native validation."""
    import NXOpen as nx

    from nx_mcp.simcenter.boundary_state import capture_effective_membership
    from nx_mcp.simcenter.collector_state import state_hash

    if type(enabled) is not bool:
        raise NXToolError("NX_INVALID_ARGUMENT", "enabled must be a boolean")
    sol = sim.Simulation.ActiveSolution
    if (
        session.Parts.BaseWork != sim
        or sol is None
        or sol.SolverType != "NX MULTIPHYSICS"
        or sol.AnalysisType not in ("Flow", "Coupled Thermal-Flow")
        or sol.StepCount != 1
        or list(sim.Simulation.Solutions) != [sol]
    ):
        raise NXToolError("NX_SIM_SOLUTION_TYPE", "Activate a single-step Multiphysics flow SIM")
    binding = inspect(boundary, sim, require_member=False)
    inventory = snapshot(sim)
    if int(boundary.Tag) not in inventory["objects"]:
        raise NXToolError("NX_SIM_SELECTION_OWNER", "Fan is not in this SIM's object inventory")
    membership = capture_effective_membership(sim)
    if not membership["comparison_verified"]:
        raise NXToolError(
            "NX_SIM_UNSUPPORTED_CONFIGURATION", "Membership must be fully readable and unfoldered"
        )
    ref = {"journal_id": boundary.JournalIdentifier, "owner_path": sim.FullPath}
    if any(ref in step["bcs"] for step in membership["steps"]):
        raise NXToolError(
            "NX_SIM_UNSUPPORTED_CONFIGURATION", "Step-level fan membership is unsupported"
        )
    present = ref in membership["solution"]["bcs"]
    if present != (int(boundary.Tag) in inventory["solution_bcs"]):
        raise NXToolError("NX_SIM_READBACK_MISMATCH", "Fan membership observations disagree")
    result = {
        "changed": present != enabled,
        "enabled_in_active_solution": enabled,
        "saved": False,
        "solver_launched": False,
        "native_export_effectiveness": "not_verified",
        "fan_properties_preserved": binding,
    }
    if present == enabled:
        return result
    expected = deepcopy(membership)
    for key in ("bcs", "unfoldered_bcs"):
        values = expected["solution"][key]
        if enabled:
            values.append(ref)
            values.sort(key=lambda row: row["journal_id"])
        else:
            values.remove(ref)
    expected["sha256"] = state_hash({"solution": expected["solution"], "steps": expected["steps"]})
    expected_inventory = deepcopy(inventory)
    tags = expected_inventory["solution_bcs"]
    if enabled:
        tags.append(int(boundary.Tag))
        tags.sort()
    else:
        tags.remove(int(boundary.Tag))
    mark = session.SetUndoMark(nx.Session.MarkVisibility.Visible, "NX MCP Internal Fan membership")
    try:
        (sol.AddBc if enabled else sol.RemoveBc)(boundary)
        if session.UpdateManager.DoUpdate(mark):
            raise NXToolError("NX_SIM_UPDATE_FAILED", "Fan membership update reported errors")
        after = snapshot(sim)
        if (
            capture_effective_membership(sim) != expected
            or inspect(boundary, sim, require_member=False) != binding
            or any(after[k] != expected_inventory[k] for k in inventory if k != "modified")
        ):
            raise NXToolError(
                "NX_SIM_READBACK_MISMATCH", "Fan membership or preserved state differs"
            )
        result["membership"] = expected
        result["results_stale"] = True
        return result
    except Exception as error:
        try:
            session.UndoToMark(mark, None)
            if (
                snapshot(sim) != inventory
                or capture_effective_membership(sim) != membership
                or inspect(boundary, sim, require_member=False) != binding
            ):
                raise RuntimeError("Fan membership rollback differs")
            session.DeleteUndoMark(mark, None)
        except Exception as recovery:
            raise NXToolError(
                "NX_SIM_ROLLBACK_FAILED",
                "Fan membership rollback incomplete",
                details={
                    "mutation_outcome": "partial",
                    "operation_error": str(error),
                    "recovery_error": str(recovery),
                },
            ) from error
        raise NXToolError(
            getattr(error, "code", "NX_SIM_AUTHORING_FAILED"),
            str(error),
            details={"mutation_outcome": "rolled_back"},
        ) from error


def edit(session, sim, boundary, volume_flow_m3_s):
    import NXOpen as nx

    if (
        type(volume_flow_m3_s) not in (int, float)
        or not math.isfinite(volume_flow_m3_s)
        or volume_flow_m3_s <= 0
    ):
        raise NXToolError("NX_INVALID_ARGUMENT", "Supply positive finite m3/s")
    sol = sim.Simulation.ActiveSolution
    if (
        session.Parts.BaseWork != sim
        or sol is None
        or sol.SolverType != "NX MULTIPHYSICS"
        or sol.AnalysisType not in ("Flow", "Coupled Thermal-Flow")
        or sol.StepCount != 1
    ):
        raise NXToolError("NX_SIM_SOLUTION_TYPE", "Activate a single-step Multiphysics flow SIM")
    before = inspect(boundary, sim)
    inventory = snapshot(sim)
    result = {
        "before_m3_s": before["flow"],
        "actual_m3_s": float(volume_flow_m3_s),
        "changed": before["flow"] != volume_flow_m3_s,
        "saved": False,
        "solver_launched": False,
        "results_stale": True,
        "native_acceptance": "pending",
    }
    if not result["changed"]:
        return result
    mark = session.SetUndoMark(nx.Session.MarkVisibility.Visible, "NX MCP Internal Fan flow edit")
    try:
        # New expression avoids modifying a shared expression used by another boundary.
        unit = sim.UnitCollection.FindObject("CubicMeterPerSecond")
        expression = sim.Expressions.CreateSystemNumberExpression(
            str(float(volume_flow_m3_s)), unit
        )
        wrapper = sim.FieldManager.CreateScalarFieldWrapperWithExpression(expression)
        boundary.PropertyTable.SetScalarFieldWrapperPropertyValue("Volume Flow", wrapper)
        if session.UpdateManager.DoUpdate(mark):
            raise NXToolError("NX_SIM_UPDATE_FAILED", "Fan flow update reported errors")
        actual = inspect(boundary, sim)
        if (
            not math.isclose(actual["flow"], volume_flow_m3_s, rel_tol=1e-12)
            or actual["invariants"] != before["invariants"]
        ):
            raise NXToolError("NX_SIM_READBACK_MISMATCH", "Fan flow or preserved settings differ")
        after = snapshot(sim)
        if any(after[k] != inventory[k] for k in ("objects", "solution_bcs")):
            raise NXToolError("NX_SIM_READBACK_MISMATCH", "Object or solution membership changed")
        result["actual_m3_s"] = actual["flow"]
        result["preserved"] = actual["invariants"]
        return result
    except Exception as error:
        try:
            session.UndoToMark(mark, None)
            if inspect(boundary, sim) != before or snapshot(sim) != inventory:
                raise RuntimeError("Fan binding or inventory not restored")
            session.DeleteUndoMark(mark, None)
        except Exception as recovery:
            raise NXToolError(
                "NX_SIM_ROLLBACK_FAILED",
                "Fan flow rollback incomplete",
                details={
                    "mutation_outcome": "partial",
                    "operation_error": str(error),
                    "recovery_error": str(recovery),
                },
            ) from error
        raise NXToolError(
            getattr(error, "code", "NX_SIM_AUTHORING_FAILED"),
            "Fan flow update failed and was rolled back",
            details={"mutation_outcome": "rolled_back", "operation_error": str(error)},
        ) from error
