"""Explicit native Internal Fan creation; solver semantics require separate validation."""

import math

from nx_mcp.runtime import NXToolError
from nx_mcp.simcenter.internal_fan import snapshot


def validate(name, direction, heat_w, flow_m3_s, table):
    if not isinstance(name, str) or not name.strip():
        raise NXToolError("NX_INVALID_ARGUMENT", "Supply a nonempty unique fan name")
    if (
        not isinstance(direction, (list, tuple))
        or len(direction) != 3
        or any(type(x) not in (int, float) or not math.isfinite(x) for x in direction)
    ):
        raise NXToolError("NX_INVALID_ARGUMENT", "Supply three finite direction components")
    length = math.hypot(*direction)
    if not math.isfinite(length) or length <= 0:
        raise NXToolError("NX_INVALID_ARGUMENT", "Fan direction must be nonzero and finite")
    if type(heat_w) not in (int, float) or not math.isfinite(heat_w) or heat_w < 0:
        raise NXToolError("NX_INVALID_ARGUMENT", "Motor heat must be finite nonnegative watts")
    if (flow_m3_s is None) == (table is None):
        raise NXToolError("NX_INVALID_ARGUMENT", "Supply exactly one volume flow or fan table")
    if flow_m3_s is not None and (
        type(flow_m3_s) not in (int, float) or not math.isfinite(flow_m3_s) or flow_m3_s <= 0
    ):
        raise NXToolError("NX_INVALID_ARGUMENT", "Volume flow must be positive finite m3/s")
    return [x / length for x in direction]


def creation_snapshot(sim):
    return {**snapshot(sim), "directions": sorted(int(x.Tag) for x in sim.Directions)}


def create(session, sim, faces, name, direction, heat_w, flow_m3_s=None, table=None):
    import NXOpen as nx
    import NXOpen.CAE as cae

    from nx_mcp.simcenter.boundaries import verify_face_targets
    from nx_mcp.simcenter.fan_field import inspect_fan_table
    from nx_mcp.simcenter.properties import read_properties
    from nx_mcp.simcenter.solver_guard import require_solver_idle

    vector = validate(name, direction, heat_w, flow_m3_s, table)
    if not isinstance(sim, cae.SimPart) or session.Parts.BaseWork != sim:
        raise NXToolError("NX_SIM_DOCUMENT_NOT_ACTIVE", "Activate the target SIM")
    sol = sim.Simulation.ActiveSolution
    if (
        sol is None
        or sol.SolverType != "NX MULTIPHYSICS"
        or sol.AnalysisType not in ("Flow", "Coupled Thermal-Flow")
    ):
        raise NXToolError(
            "NX_SIM_SOLUTION_TYPE", "Requires NX MULTIPHYSICS Flow or Coupled Thermal-Flow"
        )
    if not faces or len(faces) > 1000 or len({int(f.Tag) for f in faces}) != len(faces):
        raise NXToolError("NX_INVALID_ARGUMENT", "Supply 1..1000 distinct SIM occurrence faces")
    if any(f.OwningPart != sim or not f.IsOccurrence for f in faces):
        raise NXToolError("NX_SIM_SELECTION_OWNER", "Select SIM occurrence faces from nx_sim_faces")
    requested = {int(f.Tag) for f in faces}
    for obj in sim.Simulation.SimulationObjects:
        if obj.Name.casefold() == name.casefold():
            raise NXToolError("NX_SIM_NAME_CONFLICT", "Simulation object name already exists")
        if obj.DescriptorName in ("Inlet", "Opening", "Internal Fan"):
            _, members = obj.TargetSetManager.GetTargetSetMembers(0)
            if requested.intersection(int(m.Obj.Tag) for m in members):
                raise NXToolError("NX_SIM_SELECTION_OVERLAP", "Face already has a flow boundary")
    audit = None
    if table is not None:
        audit = inspect_fan_table(sim, table)
        if audit["manifest"]["pressure_convention"] != "static":
            raise NXToolError("NX_SIM_UNSUPPORTED", "Only static-pressure fan tables are supported")
    guard = require_solver_idle()
    flow_unit = sim.UnitCollection.FindObject("CubicMeterPerSecond")
    heat_unit = sim.UnitCollection.FindObject("HeatFlow_Metric2")
    before = creation_snapshot(sim)
    mark = session.SetUndoMark(nx.Session.MarkVisibility.Visible, "NX MCP Internal Fan")
    builder = None
    try:
        builder = sim.Simulation.CreateBcBuilderForSimulationObjectDescriptor("Internal Fan", name)
        props = builder.PropertyTable
        selectors = {
            "Mode Option": 3 if table is None else 4,
            "Alignment": 0,
            "Swirl": 0,
            "Controller Type": 0,
        }
        for key, value in selectors.items():
            props.SetIntegerPropertyValue(key, value)
        orientation = sim.Directions.CreateDirection(
            nx.Point3d(0.0, 0.0, 0.0), nx.Vector3d(*vector), nx.SmartObject.UpdateOption.WithinModeling
        )
        props.SetVectorPropertyValue("Orientation Vector", orientation)
        props.SetBaseScalarWithDataPropertyValue("Heat Generated by Fan", float(heat_w), heat_unit)
        if table is None:
            expression = sim.Expressions.CreateSystemNumberExpression(
                str(float(flow_m3_s)), flow_unit
            )
            wrapper = sim.FieldManager.CreateScalarFieldWrapperWithExpression(expression)
            props.SetScalarFieldWrapperPropertyValue("Volume Flow", wrapper)
        else:
            wrapper = sim.FieldManager.CreateScalarFieldWrapperWithField(table, 1.0)
            props.SetScalarFieldWrapperPropertyValue("Fan Curve", wrapper)
        members = []
        for face in faces:
            member = cae.SetObject()
            member.Obj, member.SubType, member.SubId = face, cae.CaeSetObjectSubType.NotSet, 0
            members.append(member)
        builder.TargetSetManager.SetTargetSetMembers(0, members)
        boundary = builder.CommitAddBc()
        builder.Destroy()
        builder = None
        actual = boundary.PropertyTable
        if boundary.DescriptorName != "Internal Fan" or boundary.OwningPart != sim:
            raise ValueError("Committed object descriptor/owner differs")
        if any(actual.GetIntegerPropertyValue(k) != v for k, v in selectors.items()):
            raise ValueError("Committed selectors differ")
        read_direction = actual.GetVectorPropertyValue("Orientation Vector")
        if read_direction is None or read_direction.OwningPart != sim:
            raise ValueError("Committed orientation is missing or foreign")
        v = read_direction.Vector
        actual_vector = [v.X, v.Y, v.Z]
        if any(
            not math.isclose(a, b, rel_tol=1e-12, abs_tol=1e-12)
            for a, b in zip(actual_vector, vector, strict=True)
        ):
            raise ValueError("Committed orientation differs")
        actual_heat, unit = actual.GetBaseScalarWithDataPropertyValue("Heat Generated by Fan")
        if unit.Name != heat_unit.Name or not math.isclose(
            actual_heat, heat_w, rel_tol=1e-12, abs_tol=1e-12
        ):
            raise ValueError("Committed motor heat or unit differs")
        if table is None:
            actual_flow, unit = actual.GetScalarWithDataPropertyValue("Volume Flow")
            if unit.Name != flow_unit.Name or not math.isclose(
                actual_flow, flow_m3_s, rel_tol=1e-12
            ):
                raise ValueError("Committed volume flow or unit differs")
        else:
            bound = actual.GetScalarFieldWrapperPropertyValue("Fan Curve")
            if bound.GetField() != table or bound.GetFieldScaleFactor() != 1.0:
                raise ValueError("Committed fan table binding differs")
        targets = verify_face_targets(boundary, faces)
        if int(boundary.Tag) not in {int(x.Tag) for x in sol.GetBcs()}:
            raise ValueError("Internal Fan is absent from active solution")
        return {
            "boundary": boundary,
            "descriptor": "Internal Fan",
            "targets": targets,
            "solution_member": True,
            "mode": "volume_flow" if table is None else "fan_curve",
            "volume_flow_m3_s": flow_m3_s,
            "fan_table_audit": audit,
            "motor_heat_w": actual_heat,
            "orientation_vector": actual_vector,
            "coordinate_frame": "SIM absolute Cartesian",
            "properties": read_properties(actual, nx),
            "solver_preflight": guard,
            "selection_semantics_verified": False,
            "export_semantics_verified": False,
            "numerical_acceptance": False,
            "saved": False,
            "solver_launched": False,
            "results_stale": True,
        }
    except Exception as error:
        cleanup = []
        if builder is not None:
            try:
                builder.Destroy()
            except Exception as exc:
                cleanup.append(str(exc))
        restored = False
        try:
            session.UndoToMark(mark, None)
            restored = creation_snapshot(sim) == before
            if restored:
                session.DeleteUndoMark(mark, None)
        except Exception as exc:
            cleanup.append(str(exc))
        outcome = "rolled_back" if restored and not cleanup else "partial"
        raise NXToolError(
            "NX_SIM_AUTHORING_FAILED" if outcome == "rolled_back" else "NX_SIM_RECOVERY_INCOMPLETE",
            "Internal Fan creation failed; inspect recovery evidence",
            details={
                "mutation_outcome": outcome,
                "snapshot_restored": restored,
                "operation_error": str(error),
                "cleanup_errors": cleanup,
            },
        ) from error
