"""Guarded constant-volume internal-fan edits; native acceptance required separately."""

import math

from nx_mcp.runtime import NXToolError
from nx_mcp.simcenter.internal_fan import snapshot


def inspect(boundary, sim):
    """Read the supported fan binding and the invariants this operation preserves."""
    if boundary.OwningPart != sim or boundary.DescriptorName != "Internal Fan":
        raise NXToolError("NX_SIM_SELECTION_OWNER", "Select an Internal Fan in this SIM")
    p = boundary.PropertyTable
    selectors = {
        k: p.GetIntegerPropertyValue(k)
        for k in ("Mode Option", "Alignment", "Swirl", "Controller Type")
    }
    if selectors != {"Mode Option": 3, "Alignment": 0, "Swirl": 0, "Controller Type": 0}:
        raise NXToolError(
            "NX_SIM_UNSUPPORTED_CONFIGURATION",
            "Requires prescribed volume flow, normal alignment, no swirl/controller",
        )
    wrapper = p.GetScalarFieldWrapperPropertyValue("Volume Flow")
    expression = wrapper.GetExpression() if wrapper else None
    if expression is None or wrapper.GetField() is not None:
        raise NXToolError("NX_SIM_UNSUPPORTED_CONFIGURATION", "Requires constant expression flow")
    try:
        literal = float(expression.GetFormula())
    except (ValueError, TypeError) as exc:
        raise NXToolError(
            "NX_SIM_UNSUPPORTED_CONFIGURATION", "Parameterized flow is unsupported"
        ) from exc
    value, unit = p.GetScalarWithDataPropertyValue("Volume Flow")
    if (
        unit is None
        or unit.Name != "CubicMeterPerSecond"
        or not math.isfinite(value)
        or value <= 0
        or not math.isfinite(literal)
        or expression.Units is None
        or expression.Units.Name != "CubicMeterPerSecond"
        or not math.isclose(literal, value, rel_tol=1e-12)
    ):
        raise NXToolError(
            "NX_SIM_UNSUPPORTED_CONFIGURATION", "Requires positive finite flow in m3/s"
        )
    if int(boundary.Tag) not in {int(x.Tag) for x in sim.Simulation.ActiveSolution.GetBcs()}:
        raise NXToolError("NX_SIM_SELECTION_OWNER", "Fan must belong to the active solution")
    _, members = boundary.TargetSetManager.GetTargetSetMembers(0)
    targets = sorted((int(m.Obj.Tag), str(m.SubType), int(m.SubId)) for m in members)
    if not targets:
        raise NXToolError("NX_SIM_CONFIGURATION_MISSING", "Fan has no target faces")
    direction = p.GetVectorPropertyValue("Orientation Vector")
    v = direction.Vector
    heat, heat_unit = p.GetBaseScalarWithDataPropertyValue("Heat Generated by Fan")
    return {
        "flow": float(value),
        "wrapper": int(wrapper.Tag),
        "invariants": {
            "name": boundary.Name,
            "selectors": selectors,
            "targets": targets,
            "direction": [int(direction.Tag), v.X, v.Y, v.Z],
            "heat": [heat, heat_unit.Name if heat_unit else None],
        },
    }


def edit(session, sim, boundary, volume_flow_m3_s):
    import NXOpen as nx

    if (
        type(volume_flow_m3_s) not in (int, float)
        or not math.isfinite(volume_flow_m3_s)
        or volume_flow_m3_s <= 0
    ):
        raise NXToolError("NX_INVALID_ARGUMENT", "Supply positive finite m3/s")
    sol = sim.Simulation.ActiveSolution
    if (
        session.Parts.BaseWork != sim
        or sol is None
        or sol.SolverType != "NX MULTIPHYSICS"
        or sol.AnalysisType not in ("Flow", "Coupled Thermal-Flow")
        or sol.StepCount != 1
    ):
        raise NXToolError("NX_SIM_SOLUTION_TYPE", "Activate a single-step Multiphysics flow SIM")
    before = inspect(boundary, sim)
    inventory = snapshot(sim)
    result = {
        "before_m3_s": before["flow"],
        "actual_m3_s": float(volume_flow_m3_s),
        "changed": before["flow"] != volume_flow_m3_s,
        "saved": False,
        "solver_launched": False,
        "results_stale": True,
        "native_acceptance": "pending",
    }
    if not result["changed"]:
        return result
    mark = session.SetUndoMark(nx.Session.MarkVisibility.Visible, "NX MCP Internal Fan flow edit")
    try:
        # New expression avoids modifying a shared expression used by another boundary.
        unit = sim.UnitCollection.FindObject("CubicMeterPerSecond")
        expression = sim.Expressions.CreateSystemNumberExpression(
            str(float(volume_flow_m3_s)), unit
        )
        wrapper = sim.FieldManager.CreateScalarFieldWrapperWithExpression(expression)
        boundary.PropertyTable.SetScalarFieldWrapperPropertyValue("Volume Flow", wrapper)
        if session.UpdateManager.DoUpdate(mark):
            raise NXToolError("NX_SIM_UPDATE_FAILED", "Fan flow update reported errors")
        actual = inspect(boundary, sim)
        if (
            not math.isclose(actual["flow"], volume_flow_m3_s, rel_tol=1e-12)
            or actual["invariants"] != before["invariants"]
        ):
            raise NXToolError("NX_SIM_READBACK_MISMATCH", "Fan flow or preserved settings differ")
        after = snapshot(sim)
        if any(after[k] != inventory[k] for k in ("objects", "solution_bcs")):
            raise NXToolError("NX_SIM_READBACK_MISMATCH", "Object or solution membership changed")
        result["actual_m3_s"] = actual["flow"]
        result["preserved"] = actual["invariants"]
        return result
    except Exception as error:
        try:
            session.UndoToMark(mark, None)
            if inspect(boundary, sim) != before or snapshot(sim) != inventory:
                raise RuntimeError("Fan binding or inventory not restored")
            session.DeleteUndoMark(mark, None)
        except Exception as recovery:
            raise NXToolError(
                "NX_SIM_ROLLBACK_FAILED",
                "Fan flow rollback incomplete",
                details={
                    "mutation_outcome": "partial",
                    "operation_error": str(error),
                    "recovery_error": str(recovery),
                },
            ) from error
        raise NXToolError(
            getattr(error, "code", "NX_SIM_AUTHORING_FAILED"),
            "Fan flow update failed and was rolled back",
            details={"mutation_outcome": "rolled_back", "operation_error": str(error)},
        ) from error
